server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.yu.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#Eureka的配置， 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud-provider-dept8001    #修改eureka上默认描述信息

#配置Eureka中的信息
info:
  app.name: yu
  company.name: blog--y
  authoy.name: yuzhiqiang
