server:
  port: 80

#开启降级feign。 hystrix


#Eureka配置
eureka:
  client:
    register-with-eureka: false    #不向Eureka中注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true



#feign客户端默认等待1s，如果服务端的服务大于1s，则需要修改超时时间，否则会报错
ribbon:
  ReadTimeout: 5000  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000  #指的是建立连接后从服务器读取到可用资源所用的时间。


logging:      #feign 日志
  level:
    com.yu.service.DeptClientService: debug